### ISSUE TITLE
Problem with volumes

### ISSUE THREAD

**Issue by meerestier** [CONABIO/LEDAPS#1]
Hi there,

first of all, thank you for this nice repo…

I am having difficulties connecting local folders as volumes, though. I have specified a proper path but I get:

`docker: Error response from daemon: oci runtime error: exec: "/opt/ledaps": permission denied.`

Maybe this is related to the dockerfile?

Thank you for your support…

Best regards

Lars

**Comment by meerestier** [comment]
It is somehow connected to the shell_script call in the dockerfile…

**Comment by palmoreck** [comment]
Hi,

Could you provide me your command lines that youre using, please ??

By your error, probably is something related with the execution of a file, perhaps you need to do a chmod to the shell script. Sth like this:

$chmod gou+x shell_script

And youre using the dockerfile for the folder "ledaps_cc" or which dockerfile?

Greetings

**Comment by palmoreck** [comment]
Hi, 

I've updated the Dockerfile and the shell script because a new version of HDF4

I've tested with the folder: LE70210482013001ASN00 and successfully terminated

Greetings and thanks for the issue¡
